submit_reading:
  name: Submit Meter Reading
  description: Submits readings for all tariffs of the meter (device).
  fields:
    device_id:
      name: Device
      description: The meter device to submit readings for.
      required: true
      selector:
        device:
          integration: pik_comfort_meters